name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Doxygen
      run: sudo apt-get install -y doxygen

    - name: Set up Graphviz
      run: sudo apt-get install -y graphviz

    - name: Generate Doxygen documentation
      run: |
        mkdir -p docs/html  # Create the directory to store generated documentation
        doxygen 

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        # Upload the directory where the documentation is generated
        name: doxygen-docs
        path: ./docs/html/

  deploy-docs:
    needs: generate-docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        publish_branch: gh-pages
